version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django:
    image: registry.gitlab.com/my-life-ua/rest-api
    # ports:
    #   - "8000:8000"
    depends_on:
      - postgres
    environment:
      - SECRET_KEY=#s6$ds9t*ui7@=2bt77h50w2g&i6n9p#krfb&03jk4v^%_5)i7.
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
  react:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - django
